### ISSUE TITLE
[Linux] Game server termination shows segfault

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1489]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

```
[04/02/22 12:02:22:823][map][info][action] CLIENT Raist PERFORMING ACTION 02 (SmallPacket0x01A:1061)
^C
Segmentation fault (core dumped)
```

backtrace info:

```
#0  0x00007f169aa92caf in __GI___wait4 (pid=34368, stat_loc=0x0, options=0, usage=0x0)
    at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x000055ce29e6362d in dump_backtrace () at /server/src/common/kernel.cpp:133
#2  0x000055ce29e63cbd in sig_proc (sn=<optimized out>) at /server/src/common/kernel.cpp:170
#3  <signal handler called>
#4  0x00007f169a89e7c0 in ?? () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#5  0x00007f169a8e39e3 in lua_rawgeti () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#6  0x00007f169a8f087c in luaL_unref () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#7  0x000055ce29c6c3fb in sol::stateless_reference::deref (this=<optimized out>, L=<optimized out>,
    this=<optimized out>, L=<optimized out>) at /server/src/map/utils/moduleutils.cpp:35
#8  sol::basic_reference<false>::deref (this=<optimized out>, this=<optimized out>)
    at /server/ext/sol/include/sol/sol.hpp:9333
#9  sol::basic_reference<false>::~basic_reference (this=<optimized out>, this=<optimized out>)
    at /server/ext/sol/include/sol/sol.hpp:9423
#10 sol::basic_object_base<sol::basic_reference<false> >::~basic_object_base (this=<optimized out>,
    this=<optimized out>) at /server/ext/sol/include/sol/sol.hpp:15266
#11 sol::basic_object<sol::basic_reference<false> >::~basic_object (this=<optimized out>, this=<optimized out>)
    at /server/ext/sol/include/sol/sol.hpp:15325
#12 moduleutils::Override::~Override (this=<optimized out>, this=<optimized out>)
    at /server/src/map/utils/moduleutils.cpp:35
#13 std::_Destroy<moduleutils::Override> (__pointer=<optimized out>) at /usr/include/c++/9/bits/stl_construct.h:98
#14 std::_Destroy_aux<false>::__destroy<moduleutils::Override*> (__last=<optimized out>, __first=0x55ce2b37d5e0)
    at /usr/include/c++/9/bits/stl_construct.h:108
#15 std::_Destroy<moduleutils::Override*> (__last=<optimized out>, __first=<optimized out>)
    at /usr/include/c++/9/bits/stl_construct.h:137
#16 std::_Destroy<moduleutils::Override*, moduleutils::Override> (__last=<optimized out>, __first=<optimized out>)
    at /usr/include/c++/9/bits/stl_construct.h:206
#17 std::vector<moduleutils::Override, std::allocator<moduleutils::Override> >::~vector (this=<optimized out>,
    this=<optimized out>) at /usr/include/c++/9/bits/stl_vector.h:677
#18 0x00007f169a9f68d7 in __run_exit_handlers (status=0, listp=0x7f169ab9c718 <__exit_funcs>,
    run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#19 0x00007f169a9f6a90 in __GI_exit (status=<optimized out>) at exit.c:139
#20 0x000055ce29ecbcc2 in do_final (code=0) at /server/src/map/map.cpp:319
#21 0x000055ce29c09d1d in main (argc=<optimized out>, argv=<optimized out>)
    at /server/src/common/kernel.cpp:272
```

**Comment by claywar** [comment]
Closing this as this appears similar to #1819.  If this occurs again, please raise a new issue or reopen this one
