### ISSUE TITLE
[CRASH]  Map server [Commit b500127]

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1654]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

```
#0  __pthread_clockjoin_ex (threadid=140450195306240, thread_return=0x0, clockid=<optimized out>, abstime=<optimized out>, block=<optimized out>) at pthread_join_common.c:145
        __oldtype = 0
        __err = <optimized out>
        tid = 4763
        _buffer = {__routine = 0x7fbd23e9fa60 <cleanup>, __arg = 0x7fbd1bfffd28, __canceltype = 11, __prev = 0x0}
        pd = 0x7fbd1bfff700
        self = <optimized out>
        result = 0
        pd_result = <optimized out>
#1  0x00007fbd240fc047 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x0000560a22069420 in do_final (code=1) at /home/kain/server/src/map/map.cpp:314
No locals.
#3  0x0000560a21ff9a07 in do_abort () at /home/kain/server/src/map/map.cpp:336
No locals.
#4  sig_proc (sn=<optimized out>) at /home/kain/server/src/common/kernel.cpp:171
        is_called = 0
        __FUNCTION__ = <optimized out>
#5  <signal handler called>
No locals.
#6  std::_Rb_tree<CBattleEntity*, CBattleEntity*, std::_Identity<CBattleEntity*>, std::less<CBattleEntity*>, std::allocator<CBattleEntity*> >::find (__k=<optimized out>,
    this=<optimized out>) at /usr/include/c++/9/bits/stl_tree.h:2559
        __j = <optimized out>
        __j = <optimized out>
#7  std::set<CBattleEntity*, std::less<CBattleEntity*>, std::allocator<CBattleEntity*> >::find (__x=<optimized out>, this=<optimized out>) at /usr/include/c++/9/bits/stl_set.h:795
No locals.
#8  CNotorietyContainer::remove (this=0x5c305c305c305c30, entity=0x560a633d2720) at /home/kain/server/src/map/notoriety_container.cpp:45
        entity_itr = <optimized out>
#9  0x0000560a22075849 in CEnmityContainer::Clear (this=0x560a4499e4b0, EntityID=<optimized out>) at /home/kain/server/src/map/enmity_container.cpp:69
        enmity_obj = <optimized out>
        entry = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
        enmity_obj = <optimized out>
#10 0x0000560a21fd17ac in CEnmityContainer::Clear (EntityID=<optimized out>, this=<optimized out>) at /home/kain/server/src/map/enmity_container.cpp:62
        entry = <optimized out>
        __for_range = <optimized out>
        __for_begin = <optimized out>
        __for_end = <optimized out>
        enmity_obj = <optimized out>
        enmity_obj = <optimized out>
#11 CEnmityContainer::~CEnmityContainer (this=<optimized out>, this=<optimized out>) at /home/kain/server/src/map/enmity_container.cpp:50
No locals.
#12 CMobEntity::~CMobEntity (this=<optimized out>, this=<optimized out>) at /home/kain/server/src/map/entities/mobentity.cpp:147
No locals.
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x0000560a21fc2c17 in CTrustEntity::~CTrustEntity (this=<optimized out>, this=<optimized out>) at /home/kain/server/src/map/entities/trustentity.h:49
No locals.
#14 CTrustEntity::~CTrustEntity (this=<optimized out>, this=<optimized out>) at /home/kain/server/src/map/entities/trustentity.h:49
No locals.
#15 0x0000560a220053f0 in CZoneEntities::ZoneServer (this=0x560a2574a440, tick=..., check_regions=<optimized out>) at /home/kain/server/src/map/zone_entities.cpp:1215
        PTrust = <optimized out>
        pit = <optimized out>
        trustit = {first = 1922, second = 0x560a633d2720}
#16 0x0000560a2200548f in CZone::ZoneServer (this=0x560a2574a310, tick=..., check_regions=<optimized out>) at /home/kain/server/src/map/zone.cpp:852
No locals.
#17 0x0000560a21ffd20b in zone_server (tick=..., PTask=<optimized out>) at /usr/include/c++/9/any:556
No locals.
#18 0x0000560a21d984b9 in CTaskMgr::DoTimer (tick=..., this=<optimized out>) at /usr/include/c++/9/chrono:557
        PTask = 0x560a62bd1100
        diff = {__r = -235779}
        diff = <optimized out>
        PTask = <optimized out>
#19 main (argc=<optimized out>, argv=<optimized out>) at /home/kain/server/src/common/kernel.cpp:267
        next = <optimized out>
        rfd = {fds_bits = {0 <repeats 16 times>}}
```

**Comment by Omnione** [comment]
Seems like this is caused by having trust out then using a method of warp (ring in this case) while trust are engaged.

**Comment by CatsEyeXI** [comment]
we've been able to repro this using !zone with trusts out as well...

**Comment by zach2good** [comment]
I was able to repro once, and then it seems fixed with: https://github.com/LandSandBoat/server/pull/1659

**Comment by kaincenteno** [comment]
awesome thank you @zach2good  closing this issue as the server has been stable
