### ISSUE TITLE
[MAP] Crashing due to trusts or zoning? [Commit b51586a]

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1694]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

logs:

```
/09/22 22:13:05:741][map][info][lua] fTP error: TP value is not between 1000-3000!  (print:437)
[05/09/22 22:13:10:194][map][info][info] parse: 01A | 31E2 308A 0E from user: Raist (parse:660)
[05/09/22 22:13:10:194][map][info][action] CLIENT Raist PERFORMING ACTION Spellcast (0x03) (SmallPacket0x01A:1158)
[05/09/22 22:13:10:540][map][error][navmesh] CPathFind::FindPath Entity (Eschan_Ilaerns_Euvhi - 17961058) could not find path (FindPath:346)
[05/09/22 22:13:10:944][map][error][navmesh] CPathFind::FindPath Entity (Eschan_Ilaerns_Euvhi - 17961058) could not find path (FindPath:346)
[05/09/22 22:13:11:340][map][error][navmesh] CPathFind::FindPath Entity (Eschan_Ilaerns_Euvhi - 17961058) could not find path (FindPath:346)
[05/09/22 22:13:11:740][map][error][navmesh] CPathFind::FindPath Entity (Eschan_Ilaerns_Euvhi - 17961058) could not find path (FindPath:346)
[05/09/22 22:13:12:140][map][error][navmesh] CPathFind::FindPath Entity (Eschan_Ilaerns_Euvhi - 17961058) could not find path (FindPath:346)
/bin/sh: 1: Syntax error: Bad fd number
[05/09/22 22:13:12:188][map][critical][fatalerror] --- gdb backtrace --- (dump_backtrace:141)
[05/09/22 22:13:12:188][map][critical][fatalerror]  (dump_backtrace:142)
terminate called without an active exception
```

backtrace:

```
oot@4fc18c239935:/server# gdb topaz_game core.38 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from topaz_game...
[New LWP 38]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./topaz_game'.
#0  0x00007fc05a63ecaf in __GI___wait4 (pid=2781, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
(gdb) bt
#0  0x00007fc05a63ecaf in __GI___wait4 (pid=2781, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x000000000040fabb in dump_backtrace () at /server/src/common/kernel.cpp:133
#2  sig_proc (sn=<optimized out>) at /server/src/common/kernel.cpp:170
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#5  0x00007fc05a57e859 in __GI_abort () at abort.c:79
#6  0x00007fc05a97b911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fc05a98738c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fc05a9873f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x0000000000424835 in std::thread::~thread (this=0x2) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:139
#10 std::default_delete<std::thread>::operator() (this=<optimized out>, __ptr=0x2)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:81
#11 std::unique_ptr<std::thread, std::default_delete<std::thread> >::~unique_ptr (this=0x9dd2b8 <asyncThread>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:292
#12 0x00007fc05a5a28d7 in __run_exit_handlers (status=1, listp=0x7fc05a748718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, 
    run_dtors=run_dtors@entry=true) at exit.c:108
#13 0x00007fc05a5a2a90 in __GI_exit (status=<optimized out>) at exit.c:139
#14 0x000000000079fa70 in do_final (code=1) at /server/src/map/map.cpp:325
#15 0x000000000079b65b in do_abort () at /server/src/map/map.cpp:336
#16 0x0000000000410384 in sig_proc (sn=<optimized out>) at /server/src/common/kernel.cpp:171
#17 <signal handler called>
#18 std::_Rb_tree<CBattleEntity*, CBattleEntity*, std::_Identity<CBattleEntity*>, std::less<CBattleEntity*>, std::allocator<CBattleEntity*> >::_M_begin (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_tree.h:750
#19 std::_Rb_tree<CBattleEntity*, CBattleEntity*, std::_Identity<CBattleEntity*>, std::less<CBattleEntity*>, std::allocator<CBattleEntity*> >::find
    (this=<optimized out>, __k=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_tree.h:2562
#20 std::set<CBattleEntity*, std::less<CBattleEntity*>, std::allocator<CBattleEntity*> >::find (this=<optimized out>, __x=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_set.h:795
#21 CNotorietyContainer::remove (this=0x251, entity=<optimized out>) at /server/src/map/notoriety_container.cpp:47
#22 0x0000000000786331 in CEnmityContainer::Clear (this=0x7fc03e7780c0, EntityID=<optimized out>) at /server/src/map/enmity_container.cpp:69
#23 0x000000000078605f in CEnmityContainer::~CEnmityContainer (this=0x7fc03e7780c0) at /server/src/map/enmity_container.cpp:50
#24 0x000000000049a9c3 in CMobEntity::~CMobEntity (this=0x7fc03e43d390) at /server/src/map/entities/mobentity.cpp:148
#25 0x00000000004a5fd9 in CTrustEntity::~CTrustEntity (this=0x7fc03e43d390) at /server/src/map/entities/trustentity.h:49
#26 0x000000000082ccfa in CZoneEntities::ZoneServer (this=<optimized out>, tick=..., check_regions=false) at /server/src/map/zone_entities.cpp:1216
#27 0x000000000083430a in CZone::ZoneServer (this=0x1d981b40, tick=..., check_regions=false) at /server/src/map/zone.cpp:852
#28 0x000000000083071e in zone_server (tick=..., PTask=<optimized out>) at /server/src/map/zone.cpp:85
#29 0x000000000042e618 in CTaskMgr::DoTimer (this=0x7fc03fa43e20, tick=...) at /server/src/common/taskmgr.cpp:119
#30 0x0000000000410f50 in main (argc=1, argv=<optimized out>) at /server/src/common/kernel.cpp:272
```

**Comment by kaincenteno** [comment]
after releasing trust crash:

```
Core was generated by `./topaz_game'.
#0  0x00007fe96b192caf in __GI___wait4 (pid=270, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
(gdb) bt
#0  0x00007fe96b192caf in __GI___wait4 (pid=270, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x000000000040fabd in dump_backtrace () at /server/src/common/kernel.cpp:133
#2  sig_proc (sn=<optimized out>) at /server/src/common/kernel.cpp:170
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#5  0x00007fe96b0d2859 in __GI_abort () at abort.c:79
#6  0x00007fe96b4cf911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fe96b4db38c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fe96b4db3f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x0000000000424655 in std::thread::~thread (this=0x2) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:139
#10 std::default_delete<std::thread>::operator() (this=<optimized out>, __ptr=0x2) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:81
#11 std::unique_ptr<std::thread, std::default_delete<std::thread> >::~unique_ptr (this=0x9f22b8 <asyncThread>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:292
#12 0x00007fe96b0f68d7 in __run_exit_handlers (status=1, listp=0x7fe96b29c718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#13 0x00007fe96b0f6a90 in __GI_exit (status=<optimized out>) at exit.c:139
#14 0x00000000007a9c80 in do_final (code=1) at /server/src/map/map.cpp:336
#15 0x00000000007a59eb in do_abort () at /server/src/map/map.cpp:347
#16 0x000000000041003e in sig_proc (sn=<optimized out>) at /server/src/common/kernel.cpp:171
#17 <signal handler called>
#18 std::operator==<std::unique_ptr<CState, std::default_delete<CState> >, std::unique_ptr<CState, std::default_delete<CState> >&, std::unique_ptr<CState, std::default_delete<CState> >*> (
    __x=<error reading variable: Cannot access memory at address 0x90>, __y=<error reading variable: Cannot access memory at address 0x70>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_deque.h:288
#19 std::deque<std::unique_ptr<CState, std::default_delete<CState> >, std::allocator<std::unique_ptr<CState, std::default_delete<CState> > > >::empty (this=0x60)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_deque.h:1385
#20 std::stack<std::unique_ptr<CState, std::default_delete<CState> >, std::deque<std::unique_ptr<CState, std::default_delete<CState> >, std::allocator<std::unique_ptr<CState, std::default_delete<CState> > > > >::empty (this=0x60) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_stack.h:194
#21 CAIContainer::GetCurrentState (this=0x0) at /server/src/map/ai/ai_container.cpp:308
#22 CAIContainer::IsCurrentState<CDeathState, void> (this=0x0) at /server/src/map/entities/../ai/ai_container.h:102
#23 CBattleEntity::isDead (this=0x7fe94fd29120) at /server/src/map/entities/battleentity.cpp:100
#24 CBattleEntity::isAlive (this=0x7fe94fd29120) at /server/src/map/entities/battleentity.cpp:105
#25 battleutils::ClaimMob (PDefender=<optimized out>, PAttacker=0x7fe960477d60, passing=<optimized out>) at /server/src/map/utils/battleutils.cpp:5040
#26 0x00000000006f96f8 in battleutils::TakePhysicalDamage (PAttacker=<optimized out>, PDefender=0x2f45ad90, physicalAttackType=PHYSICAL_ATTACK_TYPE::NORMAL, damage=<optimized out>, isBlocked=false,
    slot=0 '\000', tpMultiplier=1, taChar=0x0, giveTPtoVictim=<optimized out>, giveTPtoAttacker=true, isCounter=<optimized out>, isCovered=<optimized out>, POriginalTarget=0x2f45ad90)
    at /server/src/map/utils/battleutils.cpp:2154
#27 0x000000000048a96e in CBattleEntity::OnAttack (this=<optimized out>, state=..., action=...) at /server/src/map/entities/battleentity.cpp:1819
#28 0x000000000046839c in CAttackState::Update (this=0x3a2f6810, tick=...) at /server/src/map/ai/states/attack_state.cpp:66
#29 0x000000000047b7c6 in CState::DoUpdate (this=0x3a2f6810, tick=...) at /server/src/map/ai/states/state.cpp:88
#30 CAIContainer::Tick (this=0x36f13200, _tick=...) at /server/src/map/ai/ai_container.cpp:382
#31 0x00000000008419b0 in CZoneEntities::ZoneServer (this=<optimized out>, tick=..., check_regions=false) at /server/src/map/zone_entities.cpp:1452
#32 0x000000000084956a in CZone::ZoneServer (this=0x163b4980, tick=..., check_regions=false) at /server/src/map/zone.cpp:864
#33 0x00000000008456ae in zone_server (tick=..., PTask=<optimized out>) at /server/src/map/zone.cpp:85
#34 0x000000000042edb8 in CTaskMgr::DoTimer (this=0x7fe9606f0240, tick=...) at /server/src/common/taskmgr.cpp:119
#35 0x0000000000410f80 in main (argc=1, argv=<optimized out>) at /server/src/common/kernel.cpp:272
```

**Comment by kaincenteno** [comment]
closing this as no longer auto crashing after zoning in or summoning trust, the second comment battleEntity looks something related to a newer crash so leaving that issue open.
