### ISSUE TITLE
[MAP] Crash [Commit b51586a]

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1696]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

unsure if this is related to earlier post. looks different so i created a new issue

```
[05/10/22 03:38:54:665][map][info][info] parse: 01A | 3269 31FE 0E from user: Metal (parse:660)
[05/10/22 03:38:54:665][map][info][action] CLIENT Metal PERFORMING ACTION Weaponskill (0x07) (SmallPacket0x01A:1158)
[05/10/22 03:38:54:739][map][info][info] parse: 01A | 0AF5 0AF0 0E from user: Raist (parse:660)
[05/10/22 03:38:54:740][map][info][action] CLIENT Raist PERFORMING ACTION Ranged Attack (0x10) (SmallPacket0x01A:1158)
/bin/sh: 1: Syntax error: Bad fd number
[05/10/22 03:38:54:808][map][critical][fatalerror] --- gdb backtrace --- (dump_backtrace:141)
[05/10/22 03:38:54:808][map][critical][fatalerror]  (dump_backtrace:142)
terminate called without an active exception
```

```
Reading symbols from topaz_game...
[New LWP 23]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./topaz_game'.
#0  0x00007fb4624e1caf in __GI___wait4 (pid=346, stat_loc=0x0, options=0, usage=0x0)
    at ../sysdeps/unix/sysv/linux/wait4.c:27
27      ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
(gdb) bt
#0  0x00007fb4624e1caf in __GI___wait4 (pid=346, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x000000000040fabb in dump_backtrace () at /server/src/common/kernel.cpp:133
#2  sig_proc (sn=<optimized out>) at /server/src/common/kernel.cpp:170
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#5  0x00007fb462421859 in __GI_abort () at abort.c:79
#6  0x00007fb46281e911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fb46282a38c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fb46282a3f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x0000000000424835 in std::thread::~thread (this=0x2) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:139
#10 std::default_delete<std::thread>::operator() (this=<optimized out>, __ptr=0x2) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:81
#11 std::unique_ptr<std::thread, std::default_delete<std::thread> >::~unique_ptr (this=0x9dd2b8 <asyncThread>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:292
#12 0x00007fb4624458d7 in __run_exit_handlers (status=1, listp=0x7fb4625eb718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#13 0x00007fb462445a90 in __GI_exit (status=<optimized out>) at exit.c:139
#14 0x000000000079fa70 in do_final (code=1) at /server/src/map/map.cpp:325
#15 0x000000000079b65b in do_abort () at /server/src/map/map.cpp:336
#16 0x0000000000410384 in sig_proc (sn=<optimized out>) at /server/src/common/kernel.cpp:171
#17 <signal handler called>
#18 std::operator==<std::unique_ptr<CState, std::default_delete<CState> >, std::unique_ptr<CState, std::default_delete<CState> >&, std::unique_ptr<CState, std::default_delete<CState> >*> (
    __x=<error reading variable: Cannot access memory at address 0x90>, __y=<error reading variable: Cannot access memory at address 0x70>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_deque.h:288
#19 std::deque<std::unique_ptr<CState, std::default_delete<CState> >, std::allocator<std::unique_ptr<CState, std::default_delete<CState> > > >::empty (this=0x60)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_deque.h:1385
#20 std::stack<std::unique_ptr<CState, std::default_delete<CState> >, std::deque<std::unique_ptr<CState, std::default_delete<CState> >, std::allocator<std::unique_ptr<CState, std::default_delete<CState> > > > >::empty (this=0x60) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_stack.h:194
#21 CAIContainer::GetCurrentState (this=0x0) at /server/src/map/ai/ai_container.cpp:308
#22 CAIContainer::IsCurrentState<CDeathState, void> (this=0x0) at /server/src/map/entities/../ai/ai_container.h:102
#23 CBattleEntity::isDead (this=0x7fb458596340) at /server/src/map/entities/battleentity.cpp:100
#24 CBattleEntity::isAlive (this=0x7fb458596340) at /server/src/map/entities/battleentity.cpp:105
#25 battleutils::RelinquishClaim (PChar=0x7fb458dc57d0) at /server/src/map/utils/battleutils.cpp:5126
#26 0x000000000049024f in CCharEntity::OnDisengage (this=0x7fb458dc57d0, state=...) at /server/src/map/entities/charentity.cpp:747
#27 0x000000000047a8d2 in CAIContainer::Tick (this=0x7fb458941570, _tick=...) at /server/src/map/ai/ai_container.cpp:388
#28 0x000000000082cfc0 in CZoneEntities::ZoneServer (this=<optimized out>, tick=..., check_regions=false) at /server/src/map/zone_entities.cpp:1243
#29 0x000000000083430a in CZone::ZoneServer (this=0x1599f3f0, tick=..., check_regions=true) at /server/src/map/zone.cpp:852
#30 0x00000000008307d4 in zone_server_region (tick=..., PTask=<optimized out>) at /server/src/map/zone.cpp:102
#31 0x000000000042e618 in CTaskMgr::DoTimer (this=0x7fb458ed7170, tick=...) at /server/src/common/taskmgr.cpp:119
#32 0x0000000000410f50 in main (argc=1, argv=<optimized out>) at /server/src/common/kernel.cpp:272
```

**Comment by RAIST5150** [comment]
Not exactly verified yet, but the only thing I have been able to link to it in any way is the manual release/resummon of a single trust versus releasing them all to the point you return to a solo state before resummoning them.

Loosing a trust to meltdown in Sky did not appear to cause an issue when resummoned.   But twice in one day on two different jobs (99SMN AND 85 SAM) in 2 different zones (Escha Ru'aun and Shrine of Ru'Avitau, respectively), if a trust was manually released and resummoned or replaced and then we engaged a mob, game went to R0 and server crashed.  Releasing them all at once by command line and resummoning them all did not seem to cause problems.

**Comment by RAIST5150** [comment]
May want to keep an eye on when #1697 commits to base and see if we can reproduce it afterwards.

**Comment by kaincenteno** [comment]
another crash saw battlenetity on it exactly the same here it goes (now on commit [d839e8a](https://github.com/kaincenteno/server/commit/d839e8ae856e62c39043a97952ae7e9df2dc3b1b))

```
[New LWP 23]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./topaz_game'.
#0  0x00007feab8079caf in __GI___wait4 (pid=134, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
(gdb) bt
#0  0x00007feab8079caf in __GI___wait4 (pid=134, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x000000000040fb5d in dump_backtrace () at /server/src/common/kernel.cpp:138
#2  sig_proc (sn=<optimized out>) at /server/src/common/kernel.cpp:175
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#5  0x00007feab7fb9859 in __GI_abort () at abort.c:79
#6  0x00007feab83b6911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007feab83c238c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007feab83c23f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x0000000000424985 in std::thread::~thread (this=0x2) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/thread:139
#10 std::default_delete<std::thread>::operator() (this=<optimized out>, __ptr=0x2) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:81
#11 std::unique_ptr<std::thread, std::default_delete<std::thread> >::~unique_ptr (this=0x9f83d8 <asyncThread>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unique_ptr.h:292
#12 0x00007feab7fdd8d7 in __run_exit_handlers (status=1, listp=0x7feab8183718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#13 0x00007feab7fdda90 in __GI_exit (status=<optimized out>) at exit.c:139
#14 0x00000000007ac6b0 in do_final (code=1) at /server/src/map/map.cpp:339
#15 0x00000000007a841b in do_abort () at /server/src/map/map.cpp:350
#16 0x00000000004100de in sig_proc (sn=<optimized out>) at /server/src/common/kernel.cpp:176
#17 <signal handler called>
#18 std::operator==<std::unique_ptr<CState, std::default_delete<CState> >, std::unique_ptr<CState, std::default_delete<CState> >&, std::unique_ptr<CState, std::default_delete<CState> >*> (
    __x=<error reading variable: Cannot access memory at address 0xff000000000090>, __y=<error reading variable: Cannot access memory at address 0xff000000000070>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_deque.h:288
#19 std::deque<std::unique_ptr<CState, std::default_delete<CState> >, std::allocator<std::unique_ptr<CState, std::default_delete<CState> > > >::empty (this=0xff000000000060)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_deque.h:1385
#20 std::stack<std::unique_ptr<CState, std::default_delete<CState> >, std::deque<std::unique_ptr<CState, std::default_delete<CState> >, std::allocator<std::unique_ptr<CState, std::default_delete<CState> > > > >::empty (
    this=0xff000000000060) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_stack.h:194
#21 CAIContainer::GetCurrentState (this=0xff000000000000) at /server/src/map/ai/ai_container.cpp:308
#22 CAIContainer::IsCurrentState<CDeathState, void> (this=0xff000000000000) at /server/src/map/entities/../ai/ai_container.h:102
#23 CBattleEntity::isDead (this=0x7feaa694f1c0) at /server/src/map/entities/battleentity.cpp:100
#24 CBattleEntity::isAlive (this=0x7feaa694f1c0) at /server/src/map/entities/battleentity.cpp:105
#25 battleutils::ClaimMob (PDefender=<optimized out>, PAttacker=0x7feaa6ac0a30, passing=<optimized out>) at /server/src/map/utils/battleutils.cpp:5040
#26 0x00000000006fbbe8 in battleutils::TakePhysicalDamage (PAttacker=<optimized out>, PDefender=0x308a57d0, physicalAttackType=PHYSICAL_ATTACK_TYPE::NORMAL, damage=<optimized out>, isBlocked=false, slot=0 '\000', tpMultiplier=1, 
    taChar=0x0, giveTPtoVictim=<optimized out>, giveTPtoAttacker=true, isCounter=<optimized out>, isCovered=<optimized out>, POriginalTarget=0x308a57d0) at /server/src/map/utils/battleutils.cpp:2154
#27 0x000000000048b1a4 in CBattleEntity::OnAttack (this=<optimized out>, state=..., action=...) at /server/src/map/entities/battleentity.cpp:1821
#28 0x0000000000468c9c in CAttackState::Update (this=0x39631880, tick=...) at /server/src/map/ai/states/attack_state.cpp:66
#29 0x000000000047c0c6 in CState::DoUpdate (this=0x39631880, tick=...) at /server/src/map/ai/states/state.cpp:88
#30 CAIContainer::Tick (this=0x1ee01120, _tick=...) at /server/src/map/ai/ai_container.cpp:382
#31 0x000000000084629f in CZoneEntities::ZoneServer (this=<optimized out>, tick=..., check_regions=false) at /server/src/map/zone_entities.cpp:1463
#32 0x000000000084e19a in CZone::ZoneServer (this=0x16248a30, tick=..., check_regions=false) at /server/src/map/zone.cpp:864
#33 0x000000000084a2de in zone_server (tick=..., PTask=<optimized out>) at /server/src/map/zone.cpp:85
#34 0x000000000042f0b8 in CTaskMgr::DoTimer (this=0x7feaa6fdb6f0, tick=...) at /server/src/common/taskmgr.cpp:119
#35 0x0000000000411020 in main (argc=1, argv=<optimized out>) at /server/src/common/kernel.cpp:278
(gdb) 
```

**Comment by kaincenteno** [comment]
closing this issue as the server has been stable for the past 7 days without a crash that looks like this one
