### ISSUE TITLE
[MAP] Crash "fmt::v8::format_error"

### ISSUE THREAD

**Issue by kaincenteno** [DerpyProjectGroup/topaz#1706]
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

```
[05/12/22 01:25:45:083][map][info][action] CLIENT Raist PERFORMING ACTION Attack (0x02) (SmallPacket0x01A:1158)
[05/12/22 01:25:45:083][map][info][info] parse: 050 | 038C 0387 04 from user: Raist (parse:683)
[05/12/22 01:25:45:083][map][info][info] parse: 050 | 038C 0387 04 from user: Raist (parse:683)
[05/12/22 01:25:45:084][map][info][info] parse: 050 | 038C 0387 04 from user: Raist (parse:683)
[05/12/22 01:25:45:084][map][info][info] parse: 050 | 038C 0387 04 from user: Raist (parse:683)
[05/12/22 01:25:45:084][map][info][info] parse: 050 | 038C 0387 04 from user: Raist (parse:683)
[05/12/22 01:25:45:085][map][info][info] parse: 050 | 038C 0387 04 from user: Raist (parse:683)
[05/12/22 01:25:45:085][map][info][info] parse: 050 | 038C 0387 04 from user: Raist (parse:683)
[05/12/22 01:25:45:085][map][info][info] parse: 050 | 038C 0387 04 from user: Raist (parse:683)
[05/12/22 01:25:45:086][map][info][info] parse: 050 | 038C 0387 04 from user: Raist (parse:683)
terminate called after throwing an instance of 'fmt::v8::format_error'
  what():  argument not found

Thread 5 "topaz_game" received signal SIGABRT, Aborted.
[Switching to Thread 0x7f63dbbfa700 (LWP 93)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f63e2792859 in __GI_abort () at abort.c:79
#2  0x00007f63e2b8f911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f63e2b9b38c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f63e2b9b3f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f63e2b9b6a9 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000000000863af1 in fmt::v8::detail::error_handler::on_error (this=<optimized out>, message=<optimized out>) at /server/ext/spdlog/include/spdlog/fmt/bundled/format-inl.h:2553
#7  0x00000000004120e7 in fmt::v8::basic_printf_context<fmt::v8::appender, char>::on_error (this=0x7f63dbbf8048, message=0x7f63dbbf7ce0 "") at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:56
#8  fmt::v8::detail::get_arg<fmt::v8::basic_printf_context<fmt::v8::appender, char>, int> (ctx=..., id=<optimized out>) at /server/ext/spdlog/include/spdlog/fmt/bundled/format.h:2067
#9  fmt::v8::detail::vprintf<char, fmt::v8::basic_printf_context<fmt::v8::appender, char> >(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_printf_context<fmt::v8::appender, char> >)::{lambda(int)#1}::operator()(int) const
    (this=<optimized out>, arg_index=<optimized out>) at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:382
#10 fmt::v8::detail::vprintf<char, fmt::v8::basic_printf_context<fmt::v8::appender, char> > (buf=..., format=..., args=...) at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:425
#11 0x000000000042ce72 in fmt::v8::vsprintf<fmt::v8::basic_string_view<char>, char> (fmt=..., args=...) at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:559
#12 fmt::v8::sprintf<char const*, , char>(char const* const&) (fmt=<optimized out>) at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:576
#13 0x000000000042cf5f in SqlConnection::Query<>(char const*) (this=0x7f63dbbf85f8, 
    query=0x7f63c7adc480 "UPDATE chars SET eminence = '\f\\0G\\0J\\0L\\0N\\0K\\0M\\0\020\\09\\0V\\0T\\0U\\0]\\0\\\\\\0_\\0X\\0`\\0^\\0Z\\0b\\0I\\0a\\0Y\\0W\\0[\\0c\\0H\\0\252\001\307\v\314\v\264\017\\0\\0%\\0\\0\\0\001\\0\\0\\0\b\\0\\0\\0\a\\0\\0\\0\006\\0\\0\\0\003\\0\\0\\0\004\\0\\0\\0\227\\0\\0\\0\035\\0\\0\\0\\0\\0\\0\\0\002\\0\\0\\"...) at /server/src/common/sql.h:129
#14 SqlConnection::Async(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)::$_0::operator()(SqlConnection*) const (this=<optimized out>, sql=0x7f63dbbf85f8) at /server/src/common/sql.cpp:65
#15 std::_Function_handler<void (SqlConnection*), SqlConnection::Async(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)::$_0>::_M_invoke(std::_Any_data const&, SqlConnection*&&) (__functor=..., __args=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#16 0x00000000004247ae in std::function<void (SqlConnection*)>::operator()(SqlConnection*) const (this=0x7f63dbbf85d8, __args=0x7f63dbbf85f8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#17 SqlConnection::HandleAsync (this=0x7f63dbbf85f8) at /server/src/common/sql.cpp:81
#18 AsyncThreadBody (user=<optimized out>, passwd=<optimized out>, host=<optimized out>, port=<optimized out>, db=<optimized out>) at /server/src/common/sql.cpp:48
#19 0x00007f63e2bc7de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007f63e296a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007f63e288f163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by kaincenteno** [comment]
same error also crashed when my char logged in to White Gate, couldnt be replicated with other PCs in the server

```
[05/12/22 01:01:38:589][map][debug][debug] CZone:: Aht_Urhgan_Whitegate IncreaseZoneCounter <1> Kain (InsertPC:100)
terminate called after throwing an instance of 'fmt::v8::format_error'
  what():  argument not found

Thread 5 "topaz_game" received signal SIGABRT, Aborted.
[Switching to Thread 0x7f51c37fe700 (LWP 75)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f51ca501859 in __GI_abort () at abort.c:79
#2  0x00007f51ca8fe911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f51ca90a38c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f51ca90a3f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f51ca90a6a9 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000000000863af1 in fmt::v8::detail::error_handler::on_error (this=<optimized out>, message=<optimized out>) at /server/ext/spdlog/include/spdlog/fmt/bundled/format-inl.h:2553
#7  0x00000000004120e7 in fmt::v8::basic_printf_context<fmt::v8::appender, char>::on_error (this=0x7f51c37fc048, message=0x7f51c37fbce0 "") at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:56
#8  fmt::v8::detail::get_arg<fmt::v8::basic_printf_context<fmt::v8::appender, char>, int> (ctx=..., id=<optimized out>) at /server/ext/spdlog/include/spdlog/fmt/bundled/format.h:2067
#9  fmt::v8::detail::vprintf<char, fmt::v8::basic_printf_context<fmt::v8::appender, char> >(fmt::v8::detail::buffer<char>&, fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_printf_context<fmt::v8::appender, char> >)::{lambda(int)#1}::operator()(int) const
    (this=<optimized out>, arg_index=<optimized out>) at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:382
#10 fmt::v8::detail::vprintf<char, fmt::v8::basic_printf_context<fmt::v8::appender, char> > (buf=..., format=..., args=...) at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:425
#11 0x000000000042ce72 in fmt::v8::vsprintf<fmt::v8::basic_string_view<char>, char> (fmt=..., args=...) at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:559
#12 fmt::v8::sprintf<char const*, , char>(char const* const&) (fmt=<optimized out>) at /server/ext/spdlog/include/spdlog/fmt/bundled/printf.h:576
#13 0x000000000042cf5f in SqlConnection::Query<>(char const*) (this=0x7f51c37fc5f8, query=0x7f51c10d7430 "UPDATE chars SET set_blue_spells = '%B\026\005[HERnU!\t\\0\\0\\0\\0\\0\\0\\0\\0' WHERE charid = 11;") at /server/src/common/sql.h:129
#14 SqlConnection::Async(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)::$_0::operator()(SqlConnection*) const (this=<optimized out>, sql=0x7f51c37fc5f8) at /server/src/common/sql.cpp:65
#15 std::_Function_handler<void (SqlConnection*), SqlConnection::Async(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)::$_0>::_M_invoke(std::_Any_data const&, SqlConnection*&&) (__functor=..., __args=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300
#16 0x00000000004247ae in std::function<void (SqlConnection*)>::operator()(SqlConnection*) const (this=0x7f51c37fc5d8, __args=0x7f51c37fc5f8) at /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:688
#17 SqlConnection::HandleAsync (this=0x7f51c37fc5f8) at /server/src/common/sql.cpp:81
#18 AsyncThreadBody (user=<optimized out>, passwd=<optimized out>, host=<optimized out>, port=<optimized out>, db=<optimized out>) at /server/src/common/sql.cpp:48
#19 0x00007f51ca936de4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007f51ca6d9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007f51ca5fe163 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by kaincenteno** [comment]
After updating server to commit e9ee327 the issue wasnt able to be reproduced on my end, waiting on PCs to test in the server

**Comment by zach2good** [comment]
Should be fixed in https://github.com/LandSandBoat/server/pull/1738/commits/bb255110533afe388411d88aea42f464fddd08c9
